version: 2
jobs:
  build:
    docker:
      - image: arsaga/laravel-alpine:7.2-zip
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
      - run:
          name: Install composer dependencies
          command: composer install --no-interaction --prefer-dist
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: echo
          command: echo Hello world

workflows:
  version: 2
  build:
    jobs:
      - build