version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
  aws-ecs: circleci/aws-ecs@1.0.1
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  checkout:
    docker:
      - image: circleci/python:3-stretch-browsers
    steps:
      - checkout:
          path: ~/test-project
      - persist_to_workspace:
          root: ~/test-project
          paths:
            - .

  build_and_test:
    docker:
      - image: php:7.4-fpm-alpine
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
      - image: circleci/redis:5.0-alpine

    environment:
      - APP_ENV: testing
      - APP_DEBUG: true
      - APP_KEY: base64:hhkpZsWp2dlASp5D7nJ7ChnxwmsJPxFgndWb/WyVtkA=
      - DB_CONNECTION: mysql
      - DB_HOST: 127.0.0.1
      - DB_PORT: 3306
      - DB_USERNAME: root
      - DB_PASSWORD: root
      - DB_DATABASE: test
      - REDIS_HOST: 127.0.0.1

    working_directory: ~/test-project

    steps:
      # testing
      - attach_workspace:
          at: ~/test-project
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.json" }}
            - v1-composer-
      - run: apk --update --no-cache add curl libzip-dev libpng-dev
      - run: rm -rf /var/cache/apk/*
      - run: docker-php-ext-install pdo_mysql
      - run: docker-php-ext-install bcmath
      - run: docker-php-ext-install zip
      - run: docker-php-ext-install opcache
      - run: docker-php-ext-install gd
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
      - run: composer global require hirak/prestissimo
      - run: composer install -n --prefer-dist
      - run: apk add git
      - run: git clone https://github.com/phpredis/phpredis.git /usr/src/php/ext/redis
      - run: docker-php-ext-install redis
      - save_cache:
          paths:
            - ./vendor
          key: v1-composer-{{ checksum "composer.json" }}
      - run: apk --update --no-cache add nodejs nodejs-npm alpine-sdk
      - run: npm install
      - run: npm run production
      - run: php artisan migrate
      - run: php artisan db:seed
      - run:
          name: Run phpunit
          command: |
            php ./vendor/bin/phpunit
      - persist_to_workspace:
          root: ~/test-project
          paths:
            - .


  push_image_test_project_develop:
    docker:
      - image: circleci/python:3-stretch-browsers
    working_directory: ~/test-project
    steps:
      - attach_workspace:
          at: ~/test-project
      - setup_remote_docker
      - run:
          name: create .env
          command: |
            cat \<<EOF > .env
              AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
              AWS_S3_SECRET_ACCESS_KEY_ID=${AWS_S3_SECRET_ACCESS_KEY_ID}
            EOF
      - aws-ecr/build-and-push-image:
          checkout: false
          repo: "sample-project-app-development"
          tag: "${CIRCLE_SHA1}"
          dockerfile: Dockerfile
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: add latest tag
          command: |
            docker tag \
              ${AWS_ECR_ACCOUNT_URL}/sample-project-app-development:${CIRCLE_SHA1} \
              ${AWS_ECR_ACCOUNT_URL}/sample-project-app-development:latest
      - aws-ecr/push-image:
          repo: "sample-project-app-development"
          tag: "latest"

  deploy_web_assets_to_s3_develop:
    docker:
      #      - image: circleci/python:2.7
      - image: circleci/node:10
    working_directory: ~/test-project
    parameters:
      bucket:
        type: string
        default: ""
    steps:
      - attach_workspace:
          at: ~/test-project
      - aws-s3/sync:
          from: ./public
          to: "s3://sample-project.dev.assets/"
          overwrite: true

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout

      - build_and_test:
          requires:
            - checkout
      - push_image_test_project_develop:
          requires:
            - build_and_test
      - deploy_web_assets_to_s3_develop:
          requires:
            - push_image_test_project_develop