version: 2
jobs:
  build:
    docker:
      - image: arsaga/laravel-alpine:7.2-zip
      - image: circleci/mysql:8.0.17
          command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:YlIJx6uH3OUb3hxN+PAiJKlC+EGZ2KYi8VHxsfdJpLk=
      - DB_CONNECTION: circleci
      - TZ: Asia/Tokyo

    steps:
      - checkout
      - restore_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
      - run:
          name: Install composer dependencies
          command: composer install --no-interaction --prefer-dist
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .
            -
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install pdo_mysql

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Migration & Seeding
          working_directory: laravel
          command: php artisan migrate --seed

workflows:
  version: 2
  build:
    jobs:
      - build